---
title: "Fig_3J_MalignantCell_GSEA_HallmarkEMT"
output: html_document
date: "2026-02-17"
---

---
title: "programs_of_interest"
output: html_document
date: "2026-01-08"
---

```{r}
install.packages("msigdbr")
library(devtools)
install_github("alserglab/fgsea") # dependency for clusterprofiler

devtools::install_github("YuLab-SMU/treeio")

devtools::install_github("GuangchuangYu/ggtree") # dependency for enrichplot, which is a dependency for clusterProfiler
BiocManager::install("clusterProfiler")
```


```{r}
library(Seurat)
library(tidyr)
library(dplyr)
library(tibble)
library(readr)
library(ggplot2)
#library(ggnewscale)
library(gghalves)
library(ggpubr) # needs cmake
library(scales)
library(patchwork)
library(stringr)
library(forcats)
library(cowplot)

library(readxl)
library(msigdbr)
library(enrichplot)
```

# load data
```{r}
srt <- readRDS("~/processed_data/tumors_normalized_scaled_dimreduction_annotated_refined_miller_with_malig_states_srt_revision.rds")
srt <- readRDS("/path/to/tumor/seurat/object")
srt_malig <- subset(srt, subset = cell_type_final_no_program == "Malignant")
Idents(srt_malig) <- "timepoint"
```

# run findmarkers
```{r}
# run findmarkers with caution. each takes > 15 min.

deg_timepoint <- FindMarkers(srt_malig, ident.1 = "Post", ident.2 = "Pre") %>%
  rownames_to_column(var = "gene")


deg_timepoint_2 <- deg_timepoint %>%
  dplyr::mutate(signif = case_when(
    avg_log2FC > 1 & p_val_adj < 0.05 ~ "signif_up",
    avg_log2FC < -1 & p_val_adj < 0.05 ~ "signif_dn",
    TRUE ~ "ns"
  ))
```


#  ---GSEA Plots ---
```{r}
# Pull hallmark genesets from msigdb
hs_gsea_h <- msigdbr(species = "Homo sapiens", # change depending on species your data came from
                      category = "H") %>% 
  dplyr::select(gs_name, gene_symbol) # GSEA TERM2GENE param requireds df with geneset name and each gene symbol
```



```{r}
# FindMarkers-based GSEA
set.seed(1234) # GSEA has some random elements. set seed.

# GSEA expects a gene-named vector of decreasingly ranked LogFC values
ranked_genes <- as.numeric(deg_timepoint_2$avg_log2FC)
names(ranked_genes) <- as.character(deg_timepoint_2$gene)
ranked_genes <- sort(ranked_genes, decreasing = TRUE)

# run GSEA using the 'GSEA' function from clusterProfiler
GSEA_res_H <- GSEA(ranked_genes, TERM2GENE = hs_gsea_h, verbose = TRUE, pvalueCutoff = 0.2) 
GSEA_res_H_df <- as_tibble(GSEA_res_H@result)


```

```{r}
# export stats for genesets of interest
H_res_df <- GSEA_res_H_df %>%
  dplyr::filter(ID == "HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION")

print(H_res_df)
```


```{r fig.width= 6, fig.height=4}
p1 <- gseaplot2(GSEA_res_H, "HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION", pvalue_table = FALSE, title = "HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION")
#ggsave("/your/path/genes_genesets_of_interest/GSEA_findMarkers_HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION.pdf", width = 6, height = 5, plot = p1)
p1
```


