---
title: "Fig_4J"
output: html_document
date: "2025-12-24"
---
Looking at change in NK cell phenotype in tumor cells after CAR T infusion. Importing seurat object of expanded cohort tumor samples with full annotations including NK cell state (processing script 7) and miller annotations (processing script 8, not used.)

Look at paired analysis ppost - 

```{r}
library(Seurat)
library(tidyr)
library(ggplot2)
library(ggpubr)
library(dplyr)
library(harmony)
library(purrr)
library(cowplot)
library(rstatix)
library(ggbeeswarm)
library(ggbreak)
```

```{r}
srt_merge <- readRDS("~/processed_data/tumors_normalized_scaled_dimreduction_annotated_refined_miller_srt_revision.rds")
```

```{r}
samples <- c("P1_Pre", "P1_Post", "P4_Pre", "P4_Post", "P7_Pre", "P7_Post", "P13_Pre", "P13_Post")
srt_NK <- subset(srt_merge, subset = sample_name %in% samples)
srt_NK <- subset(srt_NK, subset = cell_type_final == "NK cell")
```

```{r}
srt_NK$sample_name %>% table()
srt_NK$NK_subtype %>% table()
```

```{r}
meta <- srt_NK@meta.data
composition_df <- meta %>% group_by(sample_name) %>%
  summarize(total_cells = n(),
            num_cd16_pos = sum(NK_subtype == "CD56Dim CD16+"),
            fraction_cd16_pos = num_cd16_pos/total_cells)
  
composition_df$patient <- word(composition_df$sample_name, start = 1L, sep = "_")
composition_df$timepoint <- word(composition_df$sample_name, start = 2L, sep = "_")

diff_df <- composition_df %>% 
  select(patient, timepoint, fraction_cd16_pos) %>%
  pivot_wider(names_from = timepoint, values_from = fraction_cd16_pos) %>%
  mutate(delta_fraction = Post - Pre,
         log2ratio_fraction = log2(Post/Pre))

diff_df$patient <- factor(diff_df$patient, levels = c("P13", "P7", "P4", "P1"))

dim(srt_NK)

```

```{r}
p <- ggplot(data = diff_df, aes(x = log2ratio_fraction, y = patient, fill = log2ratio_fraction > 0)) +
  geom_col() +
  geom_vline(xintercept = 0, linetype = "solid", color = "black") +
  scale_fill_manual(values = c("TRUE" = "firebrick3", "FALSE" = "navy"), guide = "none") +
  labs(
    x = "Change in fraction of CD56-Dim;CD16+ NK cells (log2(Post/Pre))",
    y = "Patient"
  ) +
  theme_bw() +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 14))
p

```



