---
title: "Fig_S4G_CD8_Tcell_functional_genes"
output: html_document
date: "2026-02-17"
---


```{r}
library(Seurat)
library(tidyr)
library(ggplot2)
library(ggpubr)
library(dplyr)
library(harmony)
library(purrr)
library(cowplot)
library(rstatix)
library(ggbeeswarm)
library(ggbreak)
```

# Set up and adjust metadata
```{r}
srt_merge <- readRDS("~/processed_data/tumors_normalized_scaled_dimreduction_annotated_refined_miller_srt_revision.rds")
srt_merge$sample_name <- gsub("_", " ", srt_merge$sample_name) # remove underscore from sample name
```

# 6.1) Split Violin for CD8 T cells, T cell genes of interest
```{r}
# subset to CD8 T cells
srt_merge_CD8_tcell <- subset(srt_merge, cell_type_manual_refined == "CD8 T cell")
dim(srt_merge)
dim(srt_merge_CD8_tcell)
genes_of_interest <- c("PTPRC", "CD27", "TCF7", "CCR7", "EOMES", "TBX21", "HLA-DRA", "CD38", "MKI67", "FAS", "PDCD1", "CTLA4", "HAVCR2", "LAG3")

# Extract expression and metadata
df <- FetchData(srt_merge_CD8_tcell, vars = c(genes_of_interest, "timepoint")) %>%
  tibble::rownames_to_column("cell")

# Pivot to long format
df_long <- df %>%
  pivot_longer(cols = all_of(genes_of_interest), names_to = "gene", values_to = "expression")
df_long$timepoint <- factor(df_long$timepoint, levels = c("Pre", "Post"))
df_long$gene <- factor(df_long$gene, levels = genes_of_interest)
```


# 6.4) Means only for CD8 T cells, T cell genes of interest
```{r fig.width= 10, fig.height= 5}
means_df <- df_long %>%
  dplyr::group_by(gene, timepoint) %>%
  summarize(mean_expression = mean(expression))


p1 <- ggplot(df_long, aes(x = timepoint, y = expression, fill = timepoint)) + 
  #geom_segment(data = means_df, mapping = aes(x = timepoint, y = mean_expression), stat = "identity") +
  stat_compare_means(method = "wilcox.test", label = "p.format") +  # Add Wilcoxon test
  geom_point(position = position_jitter(width = 0.35), color = "gray", size = 0.2, alpha = 0.3) +
  stat_summary(fun = "mean", geom =  "crossbar", mapping = aes(color = timepoint)) +
  facet_wrap(~gene, scales = "free_y", ncol = 7, nrow = 2) +
  theme_bw() +
  xlab("") + 
  ylab("Expression in CD8 T cells") +
  theme(
    strip.text = element_text(size = 12),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  )

#ggsave("/your/path/CD8Tcell_genes_of_interest_segmentplot.pdf", plot = p3, width = 10, height = 5)
p1
```

