---
title: "Fig_S4F_Tcell_proportion_by_sample"
output: html_document
date: "2026-02-17"
---

```{r}
library(Seurat)
library(tidyr)
library(ggplot2)
library(ggpubr)
library(dplyr)
library(harmony)
library(purrr)
library(cowplot)
library(rstatix)
library(ggbeeswarm)
library(ggbreak)
```

# Set up and adjust metadata
```{r}
srt_merge <- readRDS("/path/to/seurat/object")
#srt_merge <- readRDS("~/processed_data/tumors_normalized_scaled_dimreduction_annotated_refined_miller_srt_revision.rds")
srt_merge$sample_name <- gsub("_", " ", srt_merge$sample_name) # remove underscore from sample name
```


```{r}
immune_cells <- c(
  "CD4 T cell", "CD8 T cell", "Cycling lymphoid cell", "Regulatory T cell", "NK cell", "Macrophage", "Microglia", "Monocyte","cDC", "Neutrophil", "Cycling myeloid cell", "Plasma cell", "B cell"
)
```

# Plot T cell type abundance in tumors by sample
```{r}
srt_merge$cell_type_final_no_program %>% unique()
# set up colors
tcell_colors <- c(
  "CD4 T cell"              = "#A6CEE3",
  "CD8 T cell"              = "#B294C7",
  "Regulatory T cell"        = "#52AF43"
)

```


```{r}
immune_cells <- c(
  "CD4 T cell", "CD8 T cell", "Cycling lymphoid cell", "Regulatory T cell", "NK cell", "Macrophage", "Microglia", "Monocyte","cDC", "Neutrophil", "Cycling myeloid cell", "Plasma cell", "B cell"
)
```

```{r}
meta <- srt_merge@meta.data
# get composition of immune cell types
composition_df <- meta %>%
  filter(cell_type_manual_refined %in% immune_cells) %>%
  group_by(sample_name, cell_type_final_no_program) %>%
  summarise(n = n(), .groups = "drop") %>%
  group_by(sample_name) %>%
  mutate(proportion = n / sum(n)) %>%
  ungroup()

# get t cell fractions
tcell_df <- composition_df %>%
  filter(cell_type_final_no_program %in% names(tcell_colors))

# Compute "Other" as 1 - sum of T cells for each timepoint
other_df <- tcell_df %>%
  group_by(sample_name) %>%
  summarize(proportion = 1 - sum(proportion)) %>%
  mutate(cell_type_final_no_program = "Other immune cells")

# Combine back with T cell data
plot_df_tcell <- bind_rows(tcell_df, other_df)

# Add gray color for "Other immune cells"
tcell_colors_full <- c(tcell_colors, "Other immune cells" = "gray70")

# Ensure factors are in the correct order
plot_df_tcell$cell_type_final_no_program <- factor(plot_df_tcell$cell_type_final_no_program, levels = c( "Other immune cells", names(tcell_colors)))

sample_order <- c("P1 Pre", "P1 Post", "P4 Pre", "P4 Post", "P7 Pre", "P7 Post", "P13 Pre", "P13 Post", "P14 Post", "P16 Post")
plot_df_tcell$sample_name <- factor(plot_df_tcell$sample_name, levels = sample_order)
```

```{r}
p1 <- ggplot(plot_df_tcell, aes(x = sample_name, y = proportion, fill = cell_type_final_no_program)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = tcell_colors_full) +
  ylab("Proportion of Immune Cells") +
  xlab("Sample name") +
  coord_cartesian(ylim = c(0, 0.6)) +
  labs(fill = "Cell Type",
       title = "Proportion of T cells (out of immune cells)") +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "right",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  ) 

#ggsave(plot = p1, filename = "/your/path/cell_revisions_final/tumor_Tcell_stacked_barplot_with_all_immune_by_sample.pdf", width = 8, height = 5)
p1
```
